# Generated by Django 4.1.6 on 2023-05-04 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_userbankaccount_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbankaccount',
            name='age',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='userbankaccount',
            name='name',
            field=models.CharField(default='niya', max_length=200),
        ),
    ]
