# Generated by Django 4.1.6 on 2023-05-15 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_userbankaccount_age_userbankaccount_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keraladistrict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='nemom', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='userbankaccount',
            name='materials',
            field=models.CharField(default='debit card', max_length=200),
        ),
        migrations.AddField(
            model_name='userbankaccount',
            name='phone_number',
            field=models.IntegerField(default='8943233657'),
        ),
        migrations.CreateModel(
            name='Keralabranch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('keraladistrict', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='accounts.keraladistrict')),
            ],
        ),
        migrations.AddField(
            model_name='userbankaccount',
            name='keralabranch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.keralabranch'),
        ),
        migrations.AddField(
            model_name='userbankaccount',
            name='keraladistrict',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.keraladistrict'),
        ),
    ]
